core/nginx-ingress/release.yaml

#Descrption
Fixed NGINX Helm Repo reference name issue.
#AB223150

223150: Fixed issue with helm repo sourceref name

---

services/base/kustomization.yaml
services/base/namespace.yaml
services/base/repository.yaml
services/snd/01/kustomization.yaml
services/snd/01/services.yaml

- Adds Git Repository, Namespace 
- updates snd/01 kustomization and adds services.yaml

223622: Adds Services Customisation

---

infra/snd/01/nginx-ingress-values.yaml

Description
Renamed resource names, ADO Service connections to ADP,
AB#234076

234076: Rename CDO to ADP

---

services/base/repository.yaml
services/snd/01/services.yaml

Updated to use the application platform ACR

Updated the name of the ACR variable to the private platform ACR AB#244603

---

core/app-config-service/config-release.yaml
core/app-config-service/config-repository.yaml
core/app-config-service/kustomization.yaml
core/azure-service-operator/kustomization.yaml
core/azure-service-operator/release.yaml
core/azure-service-operator/repository.yaml
core/cert-manager/kustomization.yaml
core/cert-manager/release.yaml
core/cert-manager/repository.yaml
core/nginx-ingress/kustomization.yaml
core/nginx-ingress/release.yaml
core/nginx-ingress/repository.yaml
infra/snd/01/app-config-service-values.yaml
infra/snd/01/nginx-ingress-values.yaml
services/base/namespace.yaml
services/base/repository.yaml
services/snd/01/services.yaml

#Description
Added annotation to set ILB subnet and renamed flux config namespace to "flux-config-cluster".

249140: Internal Load balancer subnet

---

core/nginx-ingress/release.yaml
infra/snd/01/nginx-ingress-values.yaml

Added affinity config for ingress to select the system node pool by the label. 
Added Pls visibility annotation for ingress. 
AB#249140

249140: Ingress Node selector and Pls visibility annotation

---

infra/snd/01/kustomization.yaml
infra/snd/01/priority-class.yaml

*This PR contains the changes to add a default priority-class necessary for the demo-services to run*
*Relates to ADO Work Item AB#254838*

254838: Add default priority-class to infra

---

infra/snd/01/nginx-ingress-values.yaml

Changed the pls visibility to subscription.
AB#248355

248355: Pls Visibility to subscription

---

services/base/config-map.yaml

Changed the Azure App Configuration Provider namespace to flux-config
AB#249140

249140:Changed namespace to flux-config

---

core/nginx-ingress/release.yaml
infra/snd/01/nginx-ingress-values.yaml
services/base/kustomization.yaml
services/base/repository.yaml
services/snd/01/services.yaml

Use SSH Keys from paltform secrets
Enable Pod Disruption Budget 

249140: SSH Keys from paltform secrets

---

services/base/config-map.yaml
services/base/repository.yaml
services/snd/01/services.yaml

Rename platform labels to adp-platform
Relates to ADO Work Item [AB#262177](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/262177)

262177 : Rename platform labels

---

services/base/repository.yaml
services/dev/01/kustomization.yaml
services/dev/01/patch.yaml
services/dev/01/services.yaml
services/snd/01/kustomization.yaml
services/snd/01/patch.yaml
services/snd/01/services.yaml
services/snd/02/kustomization.yaml
services/snd/02/patch.yaml
services/snd/02/services.yaml
services/snd/03/kustomization.yaml
services/snd/03/patch.yaml
services/snd/03/services.yaml
services/tst/01/kustomization.yaml
services/tst/01/patch.yaml
services/tst/01/services.yaml
services/tst/02/kustomization.yaml
services/tst/02/patch.yaml
services/tst/02/services.yaml

262177: Restructure services files

---

infra/dev/01/app-config-service-values.yaml
infra/snd/01/app-config-service-values.yaml
infra/snd/02/app-config-service-values.yaml
infra/snd/03/app-config-service-values.yaml
infra/tst/01/app-config-service-values.yaml
infra/tst/02/app-config-service-values.yaml
services/base/config-map.yaml

[AB#262177](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/262177)

262177:Azure App Configuration Provider latest version

---

infra/dev/01/nginx-ingress-values.yaml
infra/snd/01/nginx-ingress-values.yaml
infra/snd/02/nginx-ingress-values.yaml
infra/snd/03/nginx-ingress-values.yaml
infra/tst/01/nginx-ingress-values.yaml
infra/tst/02/nginx-ingress-values.yaml

Set the Ingress POD allowed disruptions value to 1 for the environments.
[AB#259850](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/259850)

259850: Pdb allowed disruptions

---

core/azure-service-operator/release.yaml

Added `storage.azure.com/*` CRD
Relates to ADO Work Item [AB#292526](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/292526) 

292526: Added storage.azure.com/* crd

---

services/base/config-provider-ca-certs-flux-config.yaml
services/base/kustomization.yaml
services/base/repository.yaml

This PR contains the changes to add custom CA secrets to flux-config namespace
[AB#307513](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/307513)

307513: Add custom CA secrets for flux-config

---

core/calico/network-policies-release.yaml

Updated Calico helm chart version to 0.1.2
[AB#326112](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/326112)

326112:Calico helm chart version

---

core/reloader/reloader-release.yaml

Update reloader HA setting so the replica count setting takes effect.
[AB#366320](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/366320)

366320: Move reloader HA setting

---

infra/dev/01/kustomization.yaml
infra/dev/01/network-policies-values.yaml
infra/prd/01/kustomization.yaml
infra/prd/01/network-policies-values.yaml
infra/pre/01/kustomization.yaml
infra/pre/01/network-policies-values.yaml
infra/snd/01/kustomization.yaml
infra/snd/01/network-policies-values.yaml
infra/snd/02/kustomization.yaml
infra/snd/02/network-policies-values.yaml
infra/snd/03/kustomization.yaml
infra/snd/03/network-policies-values.yaml
infra/tst/01/kustomization.yaml
infra/tst/01/network-policies-values.yaml
infra/tst/02/kustomization.yaml
infra/tst/02/network-policies-values.yaml

Updated version for Calico Network Policies helm charts and also added environment specific values. Environment specific configuration means we can apply network policies incrementally to upstream environments
*Link to the relevant work items: e.g: Relates to ADO Work Item [AB#305668](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/305668)

305668: Updated version for Network Policies helm chart and also added environment specific values

---

infra/dev/01/network-policies-values.yaml
infra/prd/01/network-policies-values.yaml
infra/pre/01/network-policies-values.yaml
infra/snd/01/network-policies-values.yaml
infra/snd/02/network-policies-values.yaml
infra/snd/03/network-policies-values.yaml
infra/tst/01/network-policies-values.yaml
infra/tst/02/network-policies-values.yaml

*A brief description of changes being made*
Updated the version of the Calico Network Policies Helm Chart e.g: Relates to ADO Work Item [AB#305668](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/305668)

305668: Updated version for network policies helm chart

---

clusters/snd/04/kustomization.yaml
infra/snd/04/app-config-service-values.yaml
infra/snd/04/kustomization.yaml
infra/snd/04/network-policies-values.yaml
infra/snd/04/nginx-ingress-values.yaml
services/snd/04/kustomization.yaml
services/snd/04/services.yaml

Addition of SND4 into adp-flux-core
[AB#328599](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/328599)
- [] Successful testing run(s) link provided

328599: Add SND4 to Flux-core

---

services/base/repository.yaml

Change reconcile interval for the Services repository.
Relates to ADO Work Item [AB#408229](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/408229)
N/A
N/A

408229: Change reconcile interval for the Services repository.

---

core/app-config-service/config-release.yaml
core/app-config-service/config-repository.yaml
core/azure-service-operator/release.yaml
core/azure-service-operator/repository.yaml
core/calico/api-server-release.yaml
core/calico/network-policies-release.yaml
core/calico/repository.yaml
core/cert-manager/release.yaml
core/cert-manager/repository.yaml
core/nginx-ingress/release.yaml
core/nginx-ingress/repository.yaml
core/reloader/reloader-release.yaml
core/reloader/reloader-repository.yaml
infra/dev/01/app-config-service-values.yaml
infra/dev/01/network-policies-values.yaml
infra/dev/01/nginx-ingress-values.yaml
infra/snd/03/app-config-service-values.yaml
infra/snd/03/network-policies-values.yaml
infra/snd/03/nginx-ingress-values.yaml
infra/snd/04/app-config-service-values.yaml
infra/snd/04/network-policies-values.yaml
infra/snd/04/nginx-ingress-values.yaml
infra/tst/01/app-config-service-values.yaml
infra/tst/01/network-policies-values.yaml
infra/tst/01/nginx-ingress-values.yaml
infra/tst/02/app-config-service-values.yaml
infra/tst/02/network-policies-values.yaml
infra/tst/02/nginx-ingress-values.yaml
services/base/repository.yaml

Updated Flux CRD beta versions to GA.
[AB#426169](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/426169)

426169: Flux components version updates

---

README.md
infra/prd/01/app-config-service-values.yaml
infra/prd/01/network-policies-values.yaml
infra/prd/01/nginx-ingress-values.yaml
infra/pre/01/app-config-service-values.yaml
infra/pre/01/network-policies-values.yaml
infra/pre/01/nginx-ingress-values.yaml

Flux CRD versions updated in PRE and PRD. 
[AB#426169](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/426169)

426169: Flux CRD versions in PRE and PRD

---

core/app-config-service/config-release.yaml

*A brief description of changes being made*
*Increase Horizontal Pod Autoscaling max replicas to resolve and improve alerting*
[AB#409139](https://dev.azure.com/defragovuk/DEFRA-FFC/_boards/board/t/DEFRA-FFC%20Team%20Fab/Stories?System.IterationPath=DEFRA-FFC%5CPlatform%5CFab%5CSprint21&workitem=409139)

409139: Increase app-config-service maxReplicas
